source "https://rubygems.org"

gem "fastlane", ">= 2.212.0"
gem "nokogiri"
gem "slack-notifier", "2.3.2"

plugins_path = File.join(File.dirname(__FILE__), '.', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
